package org.byteora.kyra.core.runtime;

/**
 * Loads {@link Reflector} instances generated by kyra-processor at compile time.
 */
public final class GeneratedReflectors {
    private static final String GENERATED_PACKAGE_PREFIX = "gen";

    private GeneratedReflectors() {
    }

    @SuppressWarnings("unchecked")
    public static <T> Reflector<T> load(Class<T> type) {
        try {
            return (Reflector<T>) Class.forName(reflectorTypeName(type))
                    .getConstructor()
                    .newInstance();
        } catch (ReflectiveOperationException ex) {
            throw new IllegalArgumentException("No generated reflector for type: " + type.getName(), ex);
        }
    }

    public static String reflectorTypeName(Class<?> type) {
        return generatedPackageName(type) + "." + type.getSimpleName() + "Reflector";
    }

    private static String generatedPackageName(Class<?> type) {
        String packageName = GENERATED_PACKAGE_PREFIX + "." + packageHashSegment(packageNameOf(type));
        Class<?> enclosingClass = type.getEnclosingClass();
        if (enclosingClass != null) {
            packageName += "." + packageHashSegment(enclosingClass.getName());
        }
        return packageName;
    }

    private static String packageNameOf(Class<?> type) {
        Package classPackage = type.getPackage();
        return classPackage == null ? "" : classPackage.getName();
    }

    private static String packageHashSegment(String packageName) {
        long unsignedHash = Integer.toUnsignedLong(packageName.hashCode());
        if (unsignedHash == 0L) {
            return "a";
        }
        StringBuilder builder = new StringBuilder();
        while (unsignedHash > 0L) {
            int digit = (int) (unsignedHash % 26L);
            builder.append((char) ('a' + digit));
            unsignedHash /= 26L;
        }
        return builder.reverse().toString();
    }
}
