package org.byteora.kyra.core.runtime;

import java.util.ArrayDeque;
import java.util.List;

/**
 * Loads {@link Reflector} instances generated by kyra-processor at compile time.
 */
public final class GeneratedReflectors {
    private GeneratedReflectors() {
    }

    @SuppressWarnings("unchecked")
    public static <T> Reflector<T> load(Class<T> type) {
        try {
            return (Reflector<T>) Class.forName(reflectorTypeName(type))
                    .getConstructor()
                    .newInstance();
        } catch (ReflectiveOperationException ex) {
            throw new IllegalArgumentException("No generated reflector for type: " + type.getName(), ex);
        }
    }

    public static String reflectorTypeName(Class<?> type) {
        return GeneratedNames.qualifiedName(packageNameOf(type), enclosingSimpleNames(type),
                type.getSimpleName(), "Reflector");
    }

    private static List<String> enclosingSimpleNames(Class<?> type) {
        ArrayDeque<String> names = new ArrayDeque<>();
        for (Class<?> enclosing = type.getEnclosingClass(); enclosing != null; enclosing = enclosing.getEnclosingClass()) {
            names.addFirst(enclosing.getSimpleName());
        }
        return List.copyOf(names);
    }

    private static String packageNameOf(Class<?> type) {
        Package classPackage = type.getPackage();
        return classPackage == null ? "" : classPackage.getName();
    }
}
